#!/bin/bash
set -e
export LC_ALL=C
export USE_DOCKER=1

THREADS=50
MEMORY=4096
PATH=${PATH}:$(pwd)/gitian-builder/libexec

error() {
  printf '\E[31m'; echo "$@"; printf '\E[0m'
}

if [[ $EUID -ne 0 ]]; then
    error "This script should be run using sudo"
    exit 1
fi

# Ask for Git Details
URL="https://github.com/donito-inc/donu-core"
FOLDER="$(echo $URL | grep / | cut -d/ -f5-)"
COMMIT="master"

(
   echo "Updating Git Modules"
#  git submodule init
#  git submodule update

   echo "Installing System Dependencies"
   # System Deps
#  sudo apt install -y git ruby apt-cacher-ng qemu-utils debootstrap curl docker.io &>> /dev/null 2>&1

   echo "Installing VM Builder from Git"
   # System VM Builder doesnt work with the latest versions
#  cd vmbuilder
#  sudo python setup.py install 2>&1
#  cd ..

   # Clone Repo
#  if [ ! -d "tmp/$FOLDER" ]; then
#     echo "Cloning Source Code"
#     git clone $URL tmp/$FOLDER -b $COMMIT
#  fi

   cd gitian-builder
#  echo "Building 64Bit VM"
#   bin/make-base-vm --docker --suite bionic --arch amd64

#   echo "Building 32Bit VM"
#   bin/make-base-vm --docker --suite bionic --arch i386

   # Linux
#   echo "Building Linux Binaries"
#   echo "./bin/gbuild -j ${THREADS} -m ${MEMORY} --commit $FOLDER=$COMMIT --url $FOLDER=${URL} ../tmp/$FOLDER/contrib/gitian-descriptors/gitian-linux.yml"

   ./bin/gbuild -i -j ${THREADS} -m ${MEMORY} --commit $FOLDER=$COMMIT --url $FOLDER=${URL} ../tmp/$FOLDER/contrib/gitian-descriptors/gitian-linux.yml
   mv build/out/$FOLDER-* build/out/src/$FOLDER-*.tar.gz ../binaries/

   # Windows
   echo "Building Windows Binaries"
   ./bin/gbuild -i -j ${THREADS} -m ${MEMORY} --commit $FOLDER=$COMMIT --url $FOLDER=${URL} ../tmp/$FOLDER/contrib/gitian-descriptors/gitian-win.yml
   mv build/out/$FOLDER-*-win-unsigned.tar.gz inputs/$FOLDER-win-unsigned.tar.gz
   mv build/out/$FOLDER-*.zip build/out/$FOLDER-*.exe ../binaries/

)
